"""CPU-only v0.2 source-anchor sidecar contracts.

Importing :mod:`policy_learnware_v0.v02` never imports JAX or MuJoCo.  Runtime
implementations remain behind later v0.2 modules and explicit commands.
"""

from .config import (
    AxisConfig,
    BootstrapPlan,
    COMPETENCE_MODES,
    CompetenceMode,
    MultipleTestingPlan,
    SourceChampionizationConfig,
    SourceEvaluationConfig,
    SourceFactorConfig,
    TargetFactorConfig,
    V02ConfigDraft,
    V02ConfigError,
    V02ExperimentConfig,
    load_v02_config_draft,
    load_v02_experiment_config,
    load_v02_formal_config,
)
from .schemas import (
    AxisAnchorBinding,
    EnvironmentInstanceRecord,
    EnvironmentSpec,
    ExecutionABIRecord,
    ProtocolIdentifiers,
    PublicMarketEntry,
    RuntimeContract,
    SourceAnchorRecord,
    SourceCompetenceRecord,
    TargetContextRecord,
    MODEL_DIFF_SCHEMA,
    canonical_environment_instance_projection,
    canonical_model_diff_projection,
    canonical_model_snapshot,
    derive_benchmark_protocol_id,
    derive_evaluation_protocol_id,
    derive_experiment_protocol_id,
    derive_policy_market_id,
    derive_probe_protocol_id,
    derive_protocol_id,
    derive_representation_index_id,
    derive_representation_protocol_id,
    derive_selector_protocol_id,
    derive_training_protocol_id,
    derive_live_model_diff,
)

__version__ = "0.2.0"


__all__ = [
    "AxisAnchorBinding",
    "AxisConfig",
    "BootstrapPlan",
    "COMPETENCE_MODES",
    "CompetenceMode",
    "EnvironmentInstanceRecord",
    "EnvironmentSpec",
    "ExecutionABIRecord",
    "MultipleTestingPlan",
    "MODEL_DIFF_SCHEMA",
    "ProtocolIdentifiers",
    "PublicMarketEntry",
    "RuntimeContract",
    "SourceAnchorRecord",
    "SourceChampionizationConfig",
    "SourceCompetenceRecord",
    "SourceEvaluationConfig",
    "SourceFactorConfig",
    "TargetContextRecord",
    "TargetFactorConfig",
    "V02ConfigDraft",
    "V02ConfigError",
    "V02ExperimentConfig",
    "canonical_environment_instance_projection",
    "canonical_model_diff_projection",
    "canonical_model_snapshot",
    "derive_benchmark_protocol_id",
    "derive_evaluation_protocol_id",
    "derive_experiment_protocol_id",
    "derive_policy_market_id",
    "derive_probe_protocol_id",
    "derive_protocol_id",
    "derive_representation_index_id",
    "derive_representation_protocol_id",
    "derive_selector_protocol_id",
    "derive_training_protocol_id",
    "derive_live_model_diff",
    "load_v02_config_draft",
    "load_v02_experiment_config",
    "load_v02_formal_config",
    "__version__",
]
